//
//  UIColor+OAIAdditions.m
//
//  Generated by Zeplin on 6/26/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+OAIAdditions.h"

@implementation UIColor (OAIAdditions)

+ (UIColor *)oai_redPinkColor {
	return [UIColor colorWithRed:238.0f / 255.0f green:54.0f / 255.0f blue:80.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)oai_darkNavyBlue60Color {
	return [UIColor colorWithRed:0.0f green:0.0f blue:10.0f / 255.0f alpha:0.6f];
}

+ (UIColor *)oai_darkNavyBlue40Color {
	return [UIColor colorWithRed:0.0f green:0.0f blue:10.0f / 255.0f alpha:0.4f];
}

+ (UIColor *)oai_darkNavyBlue70Color {
	return [UIColor colorWithRed:0.0f green:0.0f blue:10.0f / 255.0f alpha:0.7f];
}

+ (UIColor *)oai_redPink94Color {
	return [UIColor colorWithRed:238.0f / 255.0f green:54.0f / 255.0f blue:80.0f / 255.0f alpha:0.94f];
}

+ (UIColor *)oai_lipstickColor {
	return [UIColor colorWithRed:225.0f / 255.0f green:51.0f / 255.0f blue:76.0f / 255.0f alpha:1.0f];
}

@end
