//
//  UIColor+OAIAdditions.h
//
//  Generated by Zeplin on 6/26/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (OAIAdditions)

+ (UIColor *)oai_redPinkColor;
+ (UIColor *)oai_darkNavyBlue60Color;
+ (UIColor *)oai_darkNavyBlue40Color;
+ (UIColor *)oai_darkNavyBlue70Color;
+ (UIColor *)oai_redPink94Color;
+ (UIColor *)oai_lipstickColor;

@end
